package net.leibi.adventofcode2023.day11;

public class Input {

    public static final String SMALL = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
            """;
}
